### ISSUE TITLE
Off-site Redirects?

### ISSUE THREAD

**Issue by MeepleMe** [themorrisonagency/perch-redirects-app#2]
Any way to modify to allow off-site redirects? I want to redirect to Shopify coupon code links, which are super-long and get corrupted when sending via email.

**Comment by lachieh** [comment]
I don't believe there's anything stopping you from entering the external link as the redirect. Have you tried just entering the shopify link as the New URL?

**Comment by MeepleMe** [comment]
Only the sample text in the New URL field that says /example/redirect … I figured that meant the Perch site domain was being prepended via code. BUT NO! It totally works for off-site redirects! 

This is excellent … now I can let marketing people do their OWN redirects without touching the actual htaccess. Thank you for your work on it, and for taking the time to post it!

**Comment by lachieh** [comment]
No worries! That's exactly why I developed it! Glad it is helpful even 4 years later. I can't close this issue, can you mark as resolved?
