### ISSUE TITLE
Google Analytics Not Tracking

### ISSUE THREAD

**Issue by MeepleMe** [themorrisonagency/perch-redirects-app#3]
Redirects are logging in Google Analytics as "Direct" right now without passing along the redirect's url. So either this is …

1) Using htaccess rather than loading a page, so I'm out of luck (But hey! It's still better than it was before!)
2) Loading a page without my site's head (where my GA code is), so I need to know where the code for that page is so I can add the GA code.
3) Loading a page too fast for GA to load, so I need to know where I can add code to slow down the redirect time (5 sec is usually recommended, though annoying).

**Comment by lachieh** [comment]
This app never loads the page in the browser so it will never load client-side scripts like GA. In your use case, I'd suggest appending the URLs with a [campaign url](https://ga-dev-tools.google/campaign-url-builder/) so that the redirected page knows where the redirect came from.

**Comment by MeepleMe** [comment]
Thank you for the clarification … keeps me from going on a wild goose chase!
