### ISSUE TITLE
Category Set Order?

### ISSUE THREAD

**Issue by MeepleMe** [themorrisonagency/perch-redirects-app#4]
Does this app interact with the order in which Sets of Categories are displayed on the site? I'm dealing with a site-wide glitch that seems to have appeared around when I installed this app … all my Category Sets are being forced into alphabetical order instead of their correct manual order. But correlation isn't causation. Just want to rule out this app.

**Comment by lachieh** [comment]
It does not, the logic for this App is here:
https://github.com/themorrisonagency/perch-redirects-app/blob/cb99cb66508f38fee35e3d40055dee683934426d/perch/addons/apps/morrison_redirects/load.php#L10-L18

Effectively, the steps are like this:
- when the server receives a request, check if there are any redirects in the database
  - if there are then check if the URL matches the redirect
    - if it matches, redirect to the specified location and stop executing
- if not, continue with existing Perch logic from other apps, core, etc.

**Comment by MeepleMe** [comment]
Thank you for the clarification … kept me from going on a wild goose chase for my culprit!
